Finished 5.2 - cup of join exercise
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-EitanAb8 pull request #3
Opened 2022-03-21 21:36 UTC by EitanAb8

2022-03-22 16:18 UTC, talbarfm requested changes

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +def join(*lists, sep="-"):
give a full name - separator

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +    final_list = [inner for outer in lists[:len(lists)-1] for inner in outer+[sep]] + lists[len(lists)-1]
you can just return the list comprehension

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +        return None
https://stackoverflow.com/questions/1839289/why-should-functions-always-return-the-same-type

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +    # This function receives lists and sep sign
![Capture](https://user-images.githubusercontent.com/13467749/159524503-3b911815-bd44-4a9e-b2c7-3d52bf32bf91.JPG)

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +    # This function receives lists and sep sign
this is how I want you to document functions in python

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +
you dont need this newline

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +
remove this newline its redundant

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +    final_list = [inner for outer in lists[:len(lists)-1] for inner in outer+[sep]] + lists[len(lists)-1]
spaces around arithmetic operators - not including the ones in the []

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +    final_list = [inner for outer in lists[:len(lists)-1] for inner in outer+[sep]] + lists[len(lists)-1]
lists[:len(lists)-1] is equivalent to lists[:-1]

2022-03-22 16:18 UTC, talbarfm commented on cup_of_join.py
> +    final_list = [inner for outer in lists[:len(lists)-1] for inner in outer+[sep]] + lists[len(lists)-1]
Nice nested list comprehension

2022-03-22 17:02 UTC, talbarfm commented
Add type hints and return types to all of your functions as well

2022-03-30 08:09 UTC, lovodkin93 approved these changes
good job!

2022-03-30 08:09 UTC, merged