Finished 5.2 - piece of cake exercise
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-EitanAb8 pull request #4
Opened 2022-03-21 21:38 UTC by EitanAb8

2022-03-22 17:13 UTC, talbarfm requested changes

2022-03-22 17:13 UTC, talbarfm commented on piece_of_cake.py
> +    # This function receives:
![Capture](https://user-images.githubusercontent.com/13467749/159534315-3f2e27af-22c2-4916-a3bb-b1de860c33f9.JPG)

2022-03-22 17:13 UTC, talbarfm commented on piece_of_cake.py
> +        final_price += price*(ingredients[name]/100) if name in ingredients.keys() else 0
space around operators

2022-03-22 17:13 UTC, talbarfm commented on piece_of_cake.py
> +        final_price += price*(ingredients[name]/100) if name in ingredients.keys() else 0
ingredients[name]/100 makes less sense then price/100 - you want the cost per gram multiplied by the amount of grams, not the cost per a 100 grams multiplies by the amount/100, even though the result is the same

2022-03-22 17:13 UTC, talbarfm commented on piece_of_cake.py
> +    # This function receives:
document in this format

2022-03-22 17:13 UTC, talbarfm commented on piece_of_cake.py
> +    for name, price in prices.items():
replace this for loop with reduce function from itertools

2022-03-22 17:13 UTC, talbarfm commented on piece_of_cake.py
> +
you dont need this newline

2022-03-30 08:07 UTC, lovodkin93 approved these changes
good job!

2022-03-30 08:10 UTC, merged